window.TIMEOUT_WALLPAPER_IMAGES = [
  "10-10-6k.jpg",
  "10-11-6k.jpg",
  "10-12-6k.jpg",
  "10-13-6k.jpg",
  "10-15-Day.jpg",
  "10-15-Night.jpg",
  "14-Sonoma-Horizon.png",
  "15-Sequoia-Sunrise.png",
  "26-Tahoe-Beach-Dawn.png",
  "26-Tahoe-Beach-Day.png",
  "26-Tahoe-Beach-Dusk.png",
  "35238390255_b7955451bd_o.jpg",
  "Aerial01.jpg",
  "Aerial02.jpg",
  "Aerial03.jpg",
  "Aerial04.jpg",
  "Aerial05.jpg",
  "Aerial06.jpg",
  "Aerial07.jpg",
  "Aerial08.jpg",
  "Aerial09.jpg",
  "Antelope Canyon-02.jpg",
  "Appearance Dynamic.heic",
  "Appearance Dynamic_1.png",
  "Appearance Dynamic_2.png",
  "Appearance Dynamic_3.png",
  "Appearance Dynamic_4.png",
  "Appearance Dynamic_5.png",
  "Appearance Dynamic_6.png",
  "Appearance Dynamic_7.png",
  "Appearance Dynamic_8.png",
  "Big Sur Aerial.heic",
  "Big Sur Coastline.heic",
  "Big Sur Horizon.heic",
  "Big Sur Mountains.heic",
  "Big Sur Night Grasses.heic",
  "Big Sur Night Succulents.heic",
  "Big Sur Road.heic",
  "Big Sur Shore Rocks.heic",
  "Big Sur Waters Edge.heic",
  "Big Sur.heic",
  "Catalina Clouds.heic",
  "Catalina Coast.heic",
  "Catalina Evening.heic",
  "Catalina Rock.heic",
  "Catalina Shoreline.heic",
  "Catalina Silhouette.heic",
  "Catalina Sunset.heic",
  "Catalina.heic",
  "Color Burst 1.jpg",
  "Color Burst 2.jpg",
  "Color Burst 3.jpg",
  "Cosmos01.jpg",
  "Cosmos02.jpg",
  "Cosmos03.jpg",
  "Cosmos06.jpg",
  "Cosmos07.jpg",
  "Dark Mode JPEG.jpg",
  "Desert 1.jpg",
  "Desert 2.jpg",
  "Desert 3.jpg",
  "Desert 4.jpg",
  "Desert 5.jpg",
  "Desert 6.jpg",
  "Desert 7.jpg",
  "Dome-1-dragged.jpg",
  "Dome-2-dragged.jpg",
  "Dome.heic",
  "Dynamic.heic",
  "Earth Horizon.jpg",
  "El Capitan 2.jpg",
  "El Capitan.jpg",
  "Flower 1.jpg",
  "Flower 10.jpg",
  "Flower 2.jpg",
  "Flower 3.jpg",
  "Flower 4.jpg",
  "Flower 5.jpg",
  "Flower 6.jpg",
  "Flower 7.jpg",
  "Flower 8.jpg",
  "Flower 9.jpg",
  "Frog.jpg",
  "Isles.jpg",
  "Light mode JPEG.jpg",
  "Mojave (Dynamic) 01.heic",
  "Mojave (Dynamic) 02.heic",
  "Mojave (Dynamic) 03.heic",
  "Mojave (Dynamic) 04.heic",
  "Mojave (Dynamic) 05.heic",
  "Mojave (Dynamic) 06.heic",
  "Mojave (Dynamic) 07.heic",
  "Mojave (Dynamic) 08.heic",
  "Mojave (Dynamic) 09.heic",
  "Mojave (Dynamic) 10.heic",
  "Mojave (Dynamic) 11.heic",
  "Mojave (Dynamic) 12.heic",
  "Mojave (Dynamic) 13.heic",
  "Mojave (Dynamic) 14.heic",
  "Mojave (Dynamic) 15.heic",
  "Mojave (Dynamic) 16.heic",
  "Mojave Day.jpg",
  "Mojave Night.jpg",
  "NatGeo01.jpg",
  "NatGeo02.jpg",
  "NatGeo03.jpg",
  "NatGeo04.jpg",
  "NatGeo05.jpg",
  "NatGeo06.jpg",
  "NatGeo07.jpg",
  "NatGeo08.jpg",
  "NatGeo09.jpg",
  "NatGeo11.jpg",
  "NatGeo12.jpg",
  "NatGeo13.jpg",
  "NatGeo14.jpg",
  "NatGeo15.jpg",
  "NatGeo16.jpg",
  "NatGeo17.jpg",
  "NaturePatterns01.jpg",
  "NaturePatterns02.jpg",
  "NaturePatterns03.jpg",
  "NaturePatterns04.jpg",
  "NaturePatterns05.jpg",
  "NaturePatterns07.jpg",
  "NaturePatterns08.jpg",
  "Peak-1-dragged.jpg",
  "Peak-2-dragged.jpg",
  "Peak.heic",
  "Sierra 2.jpg",
  "Sierra.jpg",
  "Snow.jpg",
  "Tree-1-dragged.jpg",
  "Tree-2-dragged.jpg",
  "Tree.heic",
  "Valley-1-dragged.jpg",
  "Valley-2-dragged.jpg",
  "Valley.heic",
  "Yosemite 2.jpg",
  "Yosemite 3.jpg",
  "Yosemite 4.jpg",
  "Yosemite 5.jpg",
  "Yosemite.jpg",
  "death-valley.jpg",
  "desert.jpg",
  "foxtail-barley.jpg",
  "mountain-range.jpg"
];
